### ISSUE TITLE
How to get `as`, `cp` & `mas` params?

### ISSUE THREAD

**Issue by deadcoder0904** [sourabhbagrecha/tiktok-demo#1]
Hey I just noticed your project in `tiktok-api` dependencies section.

How did you get the `as`, `cp` & `mas` params? I've tried looking all over the internet but can't seem to figure it out. There's nothing really written about it online.

Can you share it? Also, would love to know which `apk` version of Tiktok you used to scrape data?

**Comment by sourabhbagrecha** [comment]
I think the api has been deprecated, also I am not sure where did I find those params.

**Comment by deadcoder0904** [comment]
@sourabhbagrecha no, the api perfectly works. if u do recall someday, do share it :)

**Comment by pixel-yord** [comment]
its the musically method for anti spam parameters. now they are way more advanced

**Comment by deadcoder0904** [comment]
haha thanks @pixel-yord but i never got the data so i abandoned this thing :)
